import Navbar from "@/component/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/component/footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import AuthProvider from "@/component/AuthProvider/AuthProvider";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mobile Pay Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <div className="container">
              <Navbar navLinks={[]} />
              {children}
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
